[package]
edition = "2021"
license = "Apache-2.0"
name = "uniget-screenshots"
version = "0.1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.5", features = ["serde"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
